# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payee',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
