# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_transfer', '0002_auto_20170307_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_type',
            field=models.CharField(choices=[('sa', 'Savings'), ('ca', 'Current'), ('cc', 'Credit Card')], default='sa', max_length=2),
        ),
    ]
